# The following test sequence tests the sequence of examples in
# getting-started.md.

###
CONNECT {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d6866e62b88cc1fda1914c687771c212");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "3e32442f995b961056ca135916d7d57c");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "11aec0ab53c26927df416ddaf825b5bb");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="John Doe" mail="john.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "375cf96bc98e1db94754beeb63ab220e");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d816b76a8a49527926e767854e72e7f1");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "54678dcbed0206ce2aa5da024ca8f4f6");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Jane Doe" mail="jane.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "3b95c3632823ec00432eaa227facf324");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Mike Ross" mail="mike.ross@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1901d5e4ffb42d73195284d6aa327443");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<person name="Dan Star" mail="dan.star@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c480fc90dbd1af6966cd2a5ce2308ada");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "137583ab5a8989d55872f1839c25b581");
});
%}

###
GET  {{service}}count(/table/guests/persons/person)%3E1 HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "ef9fb4dff55c86168b6d8af207bbb738");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    Where do you come from?</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "5e0d5bfdf15991ac44d146b2783562b6");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="john.doe@example.local">
    I'm from Hempstead and have a small bookstore.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "86d7f822afbeffc980ec9357f0469b0a");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="jane.doe@example.local">
    I live in Long Island and have an antique store.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "8cca292fc056514caa985aba0a7b239f");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="mike.ross@example.local">
    I live in Queens, work for a shipping company on a cargo ship.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "6a5b83da5cf49cda9d860258ee9f8ed1");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    I work and live in Yonkers as a gardener.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "b7ab868b877478a36510a62349976999");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    In this beautiful weather I arrived with my scooter.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "e27ddaa937e07df3594812c474875a14");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xml

<message from="dan.star@example.local">
    I like to look at the city.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1461b848c9836a2e272a98059099f9c6");
});
%}

###
# - URI: //conversation/message[position()<=count(//conversation/message)-5]
DELETE {{service}}0x2f2f636f6e766572736174696f6e2f6d6573736167655b706f736974696f6e28293c3d636f756e74282f2f636f6e766572736174696f6e2f6d657373616765292d355d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "ee45c9aceaeae61580c05b0baa79a1d5");
});
%}

###
# - URI: //message[@from='dan.star@example.local']
GET {{service}}0x2f2f6d6573736167655b4066726f6d3d2764616e2e73746172406578616d706c652e6c6f63616c275d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "41544e0b21a4d4a89eda4ca37ffd3fe9");
});
%}

###
# - URI: //*/@mail|//*/@from
GET {{service}}0x2f2f2a2f406d61696c7c2f2f2a2f4066726f6d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "95332b2e3e25a8b9df387ae61ebaf902");
});
%}

###
POST {{service}} HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="/">
    <xsl:for-each select="//persons/person">
Mame: <xsl:value-of select="@name"/>
Mail: <xsl:value-of select="@mail"/>
Messages:
      <xsl:variable name="mail" select="@mail"/>
      <xsl:choose>
        <xsl:when test="count(//message[@from=$mail]) &gt; 0">
          <xsl:for-each select="//message[@from=$mail]">
            <xsl:value-of select="."/>
          </xsl:for-each>
    ----
        </xsl:when>
        <xsl:otherwise>
    No messages
    ----
        </xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "48e315f283438021c8ee88e680d4f9e8");
});
%}

###
