# The following test sequence tests the sequence of examples in
# getting-started.md.

###
CONNECT {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "b2a0321b8f32f43da126cf0e384ea72b");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "31e61489a0ee97bec1ef37e33f8a45eb");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "fd965e4b65a4cdb38b41b4cbb6a9cacb");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="John Doe" mail="john.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "7e8c135715cd373a84c774510e60244b");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c6c2d456d925e19a0e6cc3def326e201");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "4762b743a9fb48b1201c049ad4679d91");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Jane Doe" mail="jane.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "0ec78037ac96af79e30c8382afb4eb0d");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Mike Ross" mail="mike.ross@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "b7b7192cfc93c36a6ecd6d9adf00c3e3");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Dan Star" mail="dan.star@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "02ae94cc3664906811c6eefd3b2bf6fd");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "06c24803d165ca67c813119a8dc4145f");
});
%}

###
GET  {{service}}count(/table/guests/persons/person)%3E1 HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "f3bb0d252faf40c45e85553dd277e38b");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    Where do you come from?</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c2c1932e01d150d2597637bf95402ee9");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="john.doe@example.local">
    I'm from Hempstead and have a small bookstore.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "32c281627e6595b17a9bcf9f1b0d4f94");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="jane.doe@example.local">
    I live in Long Island and have an antique store.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "f31d6db3eb1fb6cc85100b57f875c34b");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="mike.ross@example.local">
    I live in Queens, work for a shipping company on a cargo ship.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d6bbf28a03e8d664b75a24f2facda835");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    I work and live in Yonkers as a gardener.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "2ce50c11ed03a7f254ce0dd6216d1764");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    In this beautiful weather I arrived with my scooter.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "6b815215210c3ab22a8f5809d0605535");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    I like to look at the city.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "327f193ae5b7aeb0d4d3d11058f8ba61");
});
%}

###
# - URI: //conversation/message[position()<=count(//conversation/message)-5]
DELETE {{service}}0x2f2f636f6e766572736174696f6e2f6d6573736167655b706f736974696f6e28293c3d636f756e74282f2f636f6e766572736174696f6e2f6d657373616765292d355d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "f8efd7eaced7513c3417e708a0958b1b");
});
%}

###
# - URI: //message[@from='dan.star@example.local']
GET {{service}}0x2f2f6d6573736167655b4066726f6d3d2764616e2e73746172406578616d706c652e6c6f63616c275d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d9fc8c82b97adbf74c20b00a921c9274");
});
%}

###
# - URI: //*/@mail|//*/@from
GET {{service}}0x2f2f2a2f406d61696c7c2f2f2a2f4066726f6d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "44a52a8561f9d65c6b29ab2417cc65f7");
});
%}

###
POST {{service}} HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="/">
    <xsl:for-each select="//persons/person">
Mame: <xsl:value-of select="@name"/>
Mail: <xsl:value-of select="@mail"/>
Messages:
      <xsl:variable name="mail" select="@mail"/>
      <xsl:choose>
        <xsl:when test="count(//message[@from=$mail]) &gt; 0">
          <xsl:for-each select="//message[@from=$mail]">
            <xsl:value-of select="."/>
          </xsl:for-each>
    ----
        </xsl:when>
        <xsl:otherwise>
    No messages
    ----
        </xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "eeb15529edce36e69ca560ae88d0a81d");
});
%}

###
