# The following test sequence tests the sequence of examples in
# getting-started.md.

###
CONNECT {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d6866e62b88cc1fda1914c687771c212");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "6c37f5d8a00060c0da7b3028e71f98e1");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "44181533ad2f597ce12027d59ee80f71");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="John Doe" mail="john.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "4c1fe0143e31bc3ca94ed8751d73a39d");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "4807facdef53f549a686a1680b805439");
});
%}

###
PUT {{service}}/table%5Bnot(guests)%5D::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<guests>
  <persons/>
  <conversation/>
</guests>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "e228365c3c87b5978caa37d85385b3b8");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Jane Doe" mail="jane.doe@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "66a704ae6f0268237d6745dfd800f00f");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Mike Ross" mail="mike.ross@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "58c7826ae0dbd080c5524acf6125d097");
});
%}

###
PUT {{service}}/table/guests/persons::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<person name="Dan Star" mail="dan.star@example.local"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "67184be2019f08fbc695462f6a0c45a6");
});
%}

###
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "657fa021a628b4d2f7ca5699d92074fd");
});
%}

###
GET  {{service}}count(/table/guests/persons/person)%3E1 HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "ef9fb4dff55c86168b6d8af207bbb738");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    Where do you come from?</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "e85c951a750bce25746851857e62371e");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="john.doe@example.local">
    I'm from Hempstead and have a small bookstore.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "9b921fb8de98aab37b888e87e111b43d");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="jane.doe@example.local">
    I live in Long Island and have an antique store.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "44fcdcb57a81abc48e16d78d873e06d5");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="mike.ross@example.local">
    I live in Queens, work for a shipping company on a cargo ship.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "3e9ee7ae3034a47dd11049db3c31f949");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    I work and live in Yonkers as a gardener.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "3a3d1088ff02fec03f1398fc623e669f");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    In this beautiful weather I arrived with my scooter.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "21402ee3a77dc3ff603a47f8e2d113bd");
});
%}

###
PUT {{service}}/table/guests/conversation::last HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<message from="dan.star@example.local">
    I like to look at the city.</message>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "92f7320d70fd5bad1c71fa882557b8dc");
});
%}

###
# - URI: //conversation/message[position()<=count(//conversation/message)-5]
DELETE {{service}}0x2f2f636f6e766572736174696f6e2f6d6573736167655b706f736974696f6e28293c3d636f756e74282f2f636f6e766572736174696f6e2f6d657373616765292d355d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "dcd6b843272e6a2fe1eda7a225960b01");
});
%}

###
# - URI: //message[@from='dan.star@example.local']
GET {{service}}0x2f2f6d6573736167655b4066726f6d3d2764616e2e73746172406578616d706c652e6c6f63616c275d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "a3e9066160383e4e083faf84d6ce9a85");
});
%}

###
# - URI: //*/@mail|//*/@from
GET {{service}}0x2f2f2a2f406d61696c7c2f2f2a2f4066726f6d HTTP/1.0
Storage: {{storage_getting_started}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "fdd25624ec0044c2e97e1adf2f49eaf9");
});
%}

###
POST {{service}} HTTP/1.0
Storage: {{storage_getting_started}}
Content-Type: application/xslt+xml

<?xml version="1.0"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text"/>
  <xsl:template match="/">
    <xsl:for-each select="//persons/person">
Mame: <xsl:value-of select="@name"/>
Mail: <xsl:value-of select="@mail"/>
Messages:
      <xsl:variable name="mail" select="@mail"/>
      <xsl:choose>
        <xsl:when test="count(//message[@from=$mail]) &gt; 0">
          <xsl:for-each select="//message[@from=$mail]">
            <xsl:value-of select="."/>
          </xsl:for-each>
    ----
        </xsl:when>
        <xsl:otherwise>
    No messages
    ----
        </xsl:otherwise>
      </xsl:choose>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1a5dec9c4d3e897b8a1b65f83e5c1b90");
});
%}

###
