@service = http://127.0.0.1/xmex!
@storage = 0000000000000000000000000000000000O0 books

# Test sequence for OPTIONS requests
# OPTIONS is used to request the functions to an XPath, which is responded with
# the Allow header. This method distinguishes between XPath axis and XPath
# function and uses different Allow headers. Also the existence of the target
# on an XPath axis has an influence on the response. The method will not use
# status 404 in relation to non-existing targets, but will offer the methods
# CONNECT, OPTIONS, PUT via Allow-Header.
# If the XPath is a function, it is executed and thus validated, but without
# returning the result.
# Faulty XPath will cause the status 400.

###
# Storage is not establish 
# Expectations:
# - Status code 404 Resource Not Found
OPTIONS {{service}}/books HTTP/1.0
Storage: {{storage}}

###
# Initial request to establish the storage
# Expectations:
# - Status code 201 Resource Created
OPTIONS {{service}} HTTP/1.0
Storage: {{storage}}

###
# Initial request to establish an existing storage
# Expectations:
# - Status code 202 Accepted
OPTIONS {{service}} HTTP/1.0
Storage: {{storage}}

###
# Initial request to establish the storage
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: with a lot of UIDs 
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 1675

<book title="A1">
  <chapter title="Chapter A1-1">
    <paragraph title="Paragraph A1-1-1"/>
    <paragraph title="Paragraph A1-1-2"/>
    <paragraph title="Paragraph A1-1-3"/>
  </chapter>
  <chapter title="Chapter A1-2">
    <paragraph title="Paragraph A1-2-1"/>
    <paragraph title="Paragraph A1-2-2"/>
    <paragraph title="Paragraph A1-2-3"/>
  </chapter>
  <chapter title="Chapter A1-3">
    <paragraph title="Paragraph A1-3-1"/>
    <paragraph title="Paragraph A1-3-2"/>
    <paragraph title="Paragraph A1-3-3"/>
  </chapter>
</book>
<book title="B1">
  <chapter title="Chapter B1-1">
    <paragraph title="Paragraph B1-1-1"/>
    <paragraph title="Paragraph B1-1-2"/>
    <paragraph title="Paragraph B1-1-3"/>
  </chapter>
  <chapter title="Chapter B1-2">
    <paragraph title="Paragraph B1-2-1"/>
    <paragraph title="Paragraph B1-2-2"/>
    <paragraph title="Paragraph B1-2-3"/>
  </chapter>
  <chapter title="Chapter B1-3">
    <paragraph title="Paragraph B1-3-1"/>
    <paragraph title="Paragraph B1-3-2"/>
    <paragraph title="Paragraph B1-3-3"/>
  </chapter>
</book>
<book title="C1">
  <chapter title="Chapter C1-1">
    <paragraph title="Paragraph C1-1-1"/>
    <paragraph title="Paragraph C1-1-2"/>
    <paragraph title="Paragraph C1-1-3"/>
  </chapter>
  <chapter title="Chapter C1-2">
    <paragraph title="Paragraph C1-2-1"/>
    <paragraph title="Paragraph C1-2-2"/>
    <paragraph title="Paragraph C1-2-3"/>
  </chapter>
  <chapter title="Chapter C1-3">
    <paragraph title="Paragraph C1-3-1"/>
    <paragraph title="Paragraph C1-3-2"/>
    <paragraph title="Paragraph C1-3-3"/>
  </chapter>
</book>

###
# XPath axis addresses the document and thus has a usable target
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects header
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}/ HTTP/1.0
Storage: {{storage}}

###
# XPath axis without usable target
# Expectations:
# - Status code 400 Bad Request
# - Message: Invalid XPath axis (Invalid expression)
OPTIONS {{service}}// HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a usable target
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}/books HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a usable target
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 9x UID
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}(/books)//chapter HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a usable target
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 28x UID
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}(/books)//paragraph HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a usable target
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}/books/book HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a usable target
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects header
# - Allow: CONNECT, OPTIONS, PUT
OPTIONS {{service}}/books/book/new/new HTTP/1.0
Storage: {{storage}}

###
# XPath function has no effects
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects header
# - Allow: CONNECT, OPTIONS, GET, POST
OPTIONS {{service}}name(/books) HTTP/1.0
Storage: {{storage}}

###
# Wrong XPath function has no effects
# Because XPath functions are not evaluated or validated via OPTIPONS.
# The request checks more whether it can be processed.
# Expectations:
# - Status code 400 Bad Request
# - Message: Invalid XPath function (Unregistered function)
OPTIONS {{service}}wrong(/books) HTTP/1.0
Storage: {{storage}}

###
# XPath axis with a target attribute
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID
# - Allow: CONNECT, OPTIONS, GET, POST, PUT, PATCH, DELETE
OPTIONS {{service}}/books/book[1]/@title HTTP/1.0
Storage: {{storage}}

###
# XPath axis without a target attribute
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects header
# - Allow: CONNECT, OPTIONS, PUT
OPTIONS {{service}}/books/book[1]/@titlex HTTP/1.0
Storage: {{storage}}

###
