@service = http://127.0.0.1/xmex!
@storage = 0000000000000000000000000000000000PP books

# Test sequence for storing XML structures into storage using pseudo elements.
# Pseudo elements serve as relative navigation to elements that are addressed
# by XPath: BEFORE AFTER FIRST LAST
# They are used to relativize the position of an element. 

###
# Storage is not establish 
# Expectations:
# - Status code 404 Resource Not Found
PUT {{service}}/books/book[1]::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 22

<before id="beforeA"/>

###
# Initial request to establish the storage
# Expectations:
# - Status code 201 Resource Created
OPTIONS {{service}} HTTP/1.0
Storage: {{storage}}

###
# Initial request to establish the storage
# Expectations:
# - Status code 204 No Content
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 78

<book title="A2"/>
<book title="B2"/>
<book title="C2"/>
<book title="D2"/>

###
# Expectations:
# - Status code 204 No Content
# - before-elements are put in /books before first book (order A,B,C)
PUT {{service}}/books/book[1]::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 70

<before id="beforeA"/>
<before id="beforeB"/>
<before id="beforeC"/>

###
# Expectations:
# - Status code 204 No Content
# - after-elements are put in /books after last book (order A,B,C)
PUT {{service}}/books/book[last()]::after HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<after id="afterA"/>
<after id="afterB"/>
<after id="afterC"/>

###
# Expectations:
# - Status code 204 No Content
# - first-elements are put in /books as first elements before the existing (order A,B,C)
PUT {{service}}/books::first HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<first id="firstA"/>
<first id="firstB"/>
<first id="firstC"/>

###
# Expectations:
# - Status code 204 No Content
# - last-elements are put in /books as last elements after the existing (order A,B,C)
PUT {{service}}/books::last HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 58

<last id="lastA"/>
<last id="lastB"/>
<last id="lastC"/>

###
# Use of brackets should not be a problem
# Expectations:
# - Status code 204 No Content
# - test are put in before all last elements
PUT {{service}}(/books)//last::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 58

<test/>

###
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/books::wrong HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<wrong id="wrongA"/>
<wrong id="wrongB"/>
<wrong id="wrongC"/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/books::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<wrong id="wrongA"/>
<wrong id="wrongB"/>
<wrong id="wrongC"/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/books::after HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<wrong id="wrongA"/>
<wrong id="wrongB"/>
<wrong id="wrongC"/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/*/..::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<wrong id="wrongA"/>
<wrong id="wrongB"/>
<wrong id="wrongC"/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/books/..::before HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 64

<wrong id="wrongA"/>
<wrong id="wrongB"/>
<wrong id="wrongC"/>

###
