@service = http://127.0.0.1/xmex!
@storage = 0000000000000000000000000000000000PE books

# Test sequence for putting XML structures into storage.

###
# Storage is not establish 
# Expectations:
# - Status code 404 Resource Not Found
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 18

<book title="A1"/>

###
# Initial request to establish the storage
# Expectations:
# - Status code 201 Resource Created
OPTIONS {{service}} HTTP/1.0
Storage: {{storage}}

###
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: with 5 UIDs 
# - 4 books are overwritten
# - all new elements have the attributes ___rev and ___uid
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 78

<book title="A2"/>
<book title="B2"/>
<book title="C2"/>
<book title="D2"/>

###
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: with 5 UIDs 
# - 4 books are overwritten
# - 4 books with chapter are created
# - all new elements have the attributes ___rev and ___uid
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 230

<book title="A3">
  <chapter>Text A3</chapter>
</book>
<book title="B3">
  <chapter>Text B3</chapter>
</book>
<book title="C3">
  <chapter>Text C3</chapter>
</book>
<book title="D3">
  <chapter>Text D3</chapter>
</book>

###
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: with 5 UIDs 
# - 4 books are overwritten
# - 4 books with chapter are created
# - all new elements have the attributes ___rev and ___uid
PUT {{service}}/books HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 230

<book title="A3">
  <chapter><![CDATA[Text A3]]></chapter>
</book>
<book title="B3">
  <chapter><![CDATA[Text B3]]></chapter>
</book>
<book title="C3">
  <chapter><![CDATA[Text C3]]></chapter>
</book>
<book title="D3">
  <chapter><![CDATA[Text D3]]></chapter>
</book>

###
# Use of brackets should not be a problem
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: with 5 UIDs 
# - 4 books are overwritten
# - 4 books with chapter are created
# - all new elements have the attributes ___rev and ___uid
PUT {{service}}(/books/book)/chapter HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 230

<test/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/books/.. HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 7

<test/>

###
# PUT outside the root element, shall be ignored
# Expectations:
# - Status code 204 No Content
# - Without Storage-Effects and 5 UIDs  
# - No changes in the storage
PUT {{service}}/*/.. HTTP/1.0
Storage: {{storage}}
Content-Type: application/xslt+xml
Content-Length: 7

<test/>

###
