###
# initDatasource
# Initialization from the first player
# Expectations:
# - Status code 201 Resource Created
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "8e2ccc1e2c6771d1b305f187658def4d");
});
%}

###
# initStorage
# Initialization from the first player
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 10x UID-A 1x UID-M
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "278e990594ea408652b1ef42f58774fa");
});
%}

###
# initDatasource
# Initialization from another player
# Expectations:
# - Status code 202 Accepted
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c24da70e37ed21a67bcd924f420a252b");
});
%}

###
# initStorage
# Initialization from another player
# Expectations:
# - Status code 404 Resource Not Found
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "5b2189b9c180f89d85d119b7f9db1868");
});
%}

###
# readPlayers
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 793
GET {{service}}/snake/players!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c85d00ab152840facbaca9fb3f3fb6eb");
});
%}

###
# readBoard
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 80
GET {{service}}/snake/board!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "5c42a60ab28bd6fcd30e0cd0db9af91c");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //a/@touch
PATCH {{service}}0x2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

100

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1576f446eda6f378386679eedefd7ad5");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //b/@touch
PATCH {{service}}0x2f2f622f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

200

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "0b72cddafbf9f5691daf43f9dbd582df");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //c/@touch
PATCH {{service}}0x2f2f632f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

300

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "6955e6f1636fda69882d2753150aaa0c");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //d/@touch
PATCH {{service}}0x2f2f642f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

400

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "16cefe74a193008b537b2659d70bfca3");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //a/@touch
PATCH {{service}}0x2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

500

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "a551dd60f7765f7e9638a9f759685a97");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=1])]//a
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="a"/><field id="12" player="a"/><field id="13" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c0904c03d2cdd510bbdd6e62ceaf4223");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=1])]//b
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="21" player="b"/><field id="22" player="b"/><field id="23" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "5324462dec24f882edb891d885e7d408");
});
%}

###
# initScreenUpdate
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 491
# - URI: //players//field!json
GET {{service}}0x2f2f706c61796572732f2f6669656c64216a736f6e HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c952459aee952ae8840dff23267933e2");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 6x UID-M
# - URI: //players/*[@touch<400]|//players/*[@touch='']
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683c3430305d7c2f2f706c61796572732f2a5b40746f7563683d27275d HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "4a1cd56db6dcecf722b967cb0515bc01");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 2x UID-M
# - URI: //players/*[@touch<400]/@touch
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683c3430305d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "a5c2b08b77011a5ebe7cd0ee116a4c93");
});
%}

###
# join
# Get the next free player through set touch
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID-M
# - URI: //players/*[@touch=''][1]/@touch
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683d27275d5b315d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

700

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "9edfffc701899b5dcb25e9c9e467b753");
});
%}

###
# join
# H wants to put on the start position, but only if free, but it is occupied
# Expectations:
# - Status code 404 Resource Not Found
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}0x2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "044936499191a6b72d2667e60b57aa6b");
});
%}

###
# initKeyboardControl
# A Moves one to the right
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=14])]//a
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="12" player="a"/><field id="13" player="a"/><field id="14" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "923f4e1c487a232c1bd0c476b9c18171");
});
%}

###
# join
# H wants to put on the start position, but only if free, and it is free, because A has moved
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID-A 1x UID-M
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}0x2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "be79d49b90ccd9f2a4e691f374a0991a");
});
%}

###
# initKeyboardControl
# B moves one up and collides
# Expectations:
# - Status code 404 Resource Not Found
# - URI: //players[not(//field[@id=14])]//b
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="22" player="b"/><field id="23" player="b"/><field id="14" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "34909729d84412eb267884c3d733a64e");
});
%}

###
