###
# initDatasource
# Initialization from the first player
# Expectations:
# - Status code 201 Resource Created
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "b46241e00b8ab3106b04aade5437f4f4");
});
%}

###
# initStorage
# Initialization from the first player
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 10x UID-A 1x UID-M
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "5929df0991822321f987186f299e7eb5");
});
%}

###
# initDatasource
# Initialization from another player
# Expectations:
# - Status code 202 Accepted
OPTIONS {{service}} HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "761af69860a8862164d273309efd2f72");
});
%}

###
# initStorage
# Initialization from another player
# Expectations:
# - Status code 404 Resource Not Found
PUT {{service}}/snake%5Bnot(players)%5D%5Bnot(board)%5D::last HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<players timeout="5000">
  <a color="#000000" touch=""/>
  <b color="#0000FF" touch=""/>
  <c color="#00FF00" touch=""/>
  <d color="#00FFFF" touch=""/>
  <e color="#FF0000" touch=""/>
  <f color="#FF00FF" touch=""/>
  <g color="#FFFF00" touch=""/>
  <h color="#FFFFFF" touch=""/>
</players>
<board rows="31" cols="51"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "ba50c1f2a37bfe00dc3291e60f0855c7");
});
%}

###
# readPlayers
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 793
GET {{service}}/snake/players!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "0f341b1f9ecc67bc96f99a8da36a3c95");
});
%}

###
# readBoard
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 80
GET {{service}}/snake/board!json HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "c8ca6c6fbf0da9239fd0b6b0153240d9");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //a/@touch
PATCH {{service}}0x2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

100

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "04594d47905debdc6b08d8273655c406");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //b/@touch
PATCH {{service}}0x2f2f622f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

200

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "8cfba88b578e5201859c880cbafe93fc");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //c/@touch
PATCH {{service}}0x2f2f632f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

300

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "907efd89ee6584e1a712807d6d6281a1");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //d/@touch
PATCH {{service}}0x2f2f642f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

400

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "b2b3ea585fcc2d231a633930d59c9dcd");
});
%}

###
# initTouchUpdate
# Expectations:
# - Status code 204 No Content
# - Storage-Effects; 1x UID-M
# - URI: //a/@touch
PATCH {{service}}0x2f2f612f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

500

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d9fed21b4b49d1b848abab7feb751ed4");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=1])]//a
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="a"/><field id="12" player="a"/><field id="13" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "fee68db2bd65bda4232c4b77087e14ca");
});
%}

###
# initKeyboardControl
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=1])]//b
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d315d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="21" player="b"/><field id="22" player="b"/><field id="23" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "123660ce8d0ba2286935763e503602ec");
});
%}

###
# initScreenUpdate
# Expectations:
# - Status code 200 Success
# - Content-Type: application/json
# - Content-Length: 491
# - URI: //players//field!json
GET {{service}}0x2f2f706c61796572732f2f6669656c64216a736f6e HTTP/1.0
Storage: {{storage_snake}}

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "f6d8cc11e455c4561dd0fb6c881a97fe");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 6x UID-M
# - URI: //players/*[@touch<400]|//players/*[@touch='']
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683c3430305d7c2f2f706c61796572732f2a5b40746f7563683d27275d HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "419fc2be630b8057b35049888cbeffb8");
});
%}

###
# initPlayersCleanUp
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 2x UID-M
# - URI: //players/*[@touch<400]/@touch
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683c3430305d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "1f987f73f8b0df3637841fef1b585409");
});
%}

###
# join
# Get the next free player through set touch
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID-M
# - URI: //players/*[@touch=''][1]/@touch
PATCH {{service}}0x2f2f706c61796572732f2a5b40746f7563683d27275d5b315d2f40746f756368 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: text/plain

700

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "658fe6e85dee6b5976719868486e25cf");
});
%}

###
# join
# H wants to put on the start position, but only if free, but it is occupied
# Expectations:
# - Status code 404 Resource Not Found
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}0x2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "e145b7567fe8311070fa62ed702630b7");
});
%}

###
# initKeyboardControl
# A Moves one to the right
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 3x UID-A 1x UID-M
# - URI: //players[not(//field[@id=14])]//a
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f61 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="12" player="a"/><field id="13" player="a"/><field id="14" player="a"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "ebf91bc1b52d0264f545c3af592c94de");
});
%}

###
# join
# H wants to put on the start position, but only if free, and it is free, because A has moved
# Expectations:
# - Status code 204 No Content
# - Storage-Effects: 1x UID-A 1x UID-M
# - URI: /snake[not(//field/@id=11)]//h
PATCH  {{service}}0x2f736e616b655b6e6f74282f2f6669656c642f4069643d3131295d2f2f68 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="11" player="h"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "2d13bab39390b240d56587a1cf16a083");
});
%}

###
# initKeyboardControl
# B moves one up and collides
# Expectations:
# - Status code 404 Resource Not Found
# - URI: //players[not(//field[@id=14])]//b
PATCH {{service}}0x2f2f706c61796572735b6e6f74282f2f6669656c645b4069643d31345d295d2f2f62 HTTP/1.0
Storage: {{storage_snake}}
Content-Type: application/xslt+xml

<field id="22" player="b"/><field id="23" player="b"/><field id="14" player="b"/>

> {%
client.test("unittest", function() {
    client.assert(response.headers.valueOf("Trace-Composite-Hash") === "d88e451a08ff43ed0be83a012f971bda");
});
%}

###
